name: apiverve_duedatecalculator
description: Due Date Calculator estimates pregnancy due dates using either last menstrual period or conception date, providing comprehensive pregnancy timeline information.
version: 1.1.14
homepage: https://apiverve.com/marketplace/duedatecalculator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/duedatecalculator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
